# Generated by Django 4.2.1 on 2026-05-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_personal_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalSacrifice",
            fields=[
                (
                    "id",
                    utils.models.SnowflakeIDField(primary_key=True, serialize=False),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "sacrifice_time",
                    models.DateField(
                        blank=True, help_text="牺牲时间", null=True, verbose_name="牺牲时间"
                    ),
                ),
                (
                    "sacrifice_reason",
                    models.TextField(
                        blank=True, help_text="牺牲原因", null=True, verbose_name="牺牲原因"
                    ),
                ),
                (
                    "confirmed_sacrifice_time",
                    models.DateField(
                        blank=True, help_text="认定因公牺牲时间", null=True, verbose_name="认定因公牺牲时间"
                    ),
                ),
                (
                    "martyr_approval_time",
                    models.DateField(
                        blank=True, help_text="批烈时间", null=True, verbose_name="批烈时间"
                    ),
                ),
                (
                    "is_martyr",
                    models.CharField(
                        blank=True,
                        choices=[("0", "否"), ("1", "是")],
                        default="0",
                        help_text="是否烈士",
                        max_length=1,
                        null=True,
                        verbose_name="是否烈士",
                    ),
                ),
                (
                    "approval_document_number",
                    models.CharField(
                        blank=True,
                        help_text="认定文号",
                        max_length=200,
                        null=True,
                        verbose_name="认定文号",
                    ),
                ),
                (
                    "enjoy_hero_model_benefits",
                    models.CharField(
                        blank=True,
                        help_text="享受英模或劳模待遇",
                        max_length=200,
                        null=True,
                        verbose_name="享受英模或劳模待遇",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "info",
                    models.OneToOneField(
                        help_text="关联的基本信息记录",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sacrifice_record",
                        to="app_personal_info.PersonalInfo",
                        verbose_name="基本信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "优抚一件事-人员管理-因公牺牲人员",
                "verbose_name_plural": "优抚一件事-人员管理-因公牺牲人员",
                "db_table": "pension_personal_sacrifice",
                "ordering": ("-create_datetime",),
            },
        ),
    ]
