# Generated by Django 4.2.1 on 2026-05-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_personal_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDisability",
            fields=[
                (
                    "id",
                    utils.models.SnowflakeIDField(primary_key=True, serialize=False),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "injury_time",
                    models.DateField(blank=True, help_text="受伤时间", null=True, verbose_name="受伤时间"),
                ),
                (
                    "assessment_time",
                    models.DateField(blank=True, help_text="评定时间", null=True, verbose_name="评定时间"),
                ),
                (
                    "police_disability_assessment_time",
                    models.DateField(blank=True, help_text="人民警察伤残等级评定时间", null=True, verbose_name="人民警察伤残等级评定时间"),
                ),
                (
                    "is_work_related_injury",
                    models.CharField(
                        blank=True, choices=[("0", "否"), ("1", "是")], default="0",
                        help_text="是否因公受伤", max_length=1, null=True, verbose_name="是否因公受伤"
                    ),
                ),
                (
                    "disability_level",
                    models.CharField(blank=True, help_text="致残等级", max_length=50, null=True, verbose_name="致残等级"),
                ),
                (
                    "police_disability_level",
                    models.CharField(blank=True, help_text="人民警察伤残等级", max_length=50, null=True, verbose_name="人民警察伤残等级"),
                ),
                (
                    "disability_reason",
                    models.TextField(blank=True, help_text="伤残原因", null=True, verbose_name="伤残原因"),
                ),
                (
                    "police_category",
                    models.CharField(blank=True, help_text="警种分类", max_length=100, null=True, verbose_name="警种分类"),
                ),
                (
                    "enjoy_hero_model_benefits",
                    models.CharField(blank=True, help_text="享受英模或劳模待遇", max_length=200, null=True, verbose_name="享受英模或劳模待遇"),
                ),
                (
                    "medical_expense_reimbursement",
                    models.TextField(blank=True, help_text="医疗费用报销情况", null=True, verbose_name="医疗费用报销情况"),
                ),
                (
                    "brief_description",
                    models.TextField(blank=True, help_text="简要情况", null=True, verbose_name="简要情况"),
                ),
                (
                    "family_difficulties",
                    models.TextField(blank=True, help_text="家属存在问题与困难", null=True, verbose_name="家属存在问题与困难"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False, help_text="创建人", null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL, verbose_name="创建人",
                    ),
                ),
                (
                    "info",
                    models.OneToOneField(
                        help_text="关联的基本信息记录",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disability_record",
                        to="app_personal_info.PersonalInfo", verbose_name="基本信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "优抚一件事-人员管理-伤残人员",
                "verbose_name_plural": "优抚一件事-人员管理-伤残人员",
                "db_table": "pension_personal_disability",
                "ordering": ("-create_datetime",),
            },
        ),
    ]
