# Generated by Django 4.2.1 on 2026-03-01 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewBasis",
            fields=[
                (
                    "id",
                    utils.models.SnowflakeIDField(primary_key=True, serialize=False),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "quality_type",
                    models.CharField(
                        help_text="质量标准", max_length=100, verbose_name="质量标准"
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        help_text="记分类型", max_length=100, verbose_name="记分类型"
                    ),
                ),
                (
                    "score_content",
                    models.TextField(help_text="记分内容", verbose_name="记分内容"),
                ),
                (
                    "deduct_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="扣分值",
                        max_digits=5,
                        verbose_name="扣分值",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "执法管理-案件质量-评查依据",
                "verbose_name_plural": "执法管理-案件质量-评查依据",
                "db_table": "sys_enforcement_case_quality_review_basis",
                "ordering": ("-create_datetime",),
            },
        ),
    ]
