# Generated by Django 4.2.1 on 2026-03-04 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    utils.models.SnowflakeIDField(primary_key=True, serialize=False),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "police_number",
                    models.CharField(
                        blank=True,
                        help_text="警号",
                        max_length=100,
                        null=True,
                        verbose_name="警号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="姓名",
                        max_length=100,
                        null=True,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("0", "男"), ("1", "女")],
                        default="0",
                        help_text="性别",
                        max_length=1,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="身份证号",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="出生日期", null=True, verbose_name="出生日期"
                    ),
                ),
                (
                    "nation",
                    models.CharField(
                        blank=True,
                        help_text="民族",
                        max_length=100,
                        null=True,
                        verbose_name="民族",
                    ),
                ),
                (
                    "pension_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "因公牺牲"),
                            ("1", "病故"),
                            ("2", "伤残"),
                            ("3", "重病"),
                            ("4", "困难"),
                            ("5", "住院"),
                        ],
                        default="0",
                        help_text="抚恤类别",
                        max_length=5,
                        null=True,
                        verbose_name="抚恤类别",
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        blank=True,
                        choices=[("0", "民警"), ("1", "辅警")],
                        default="0",
                        help_text="身份",
                        max_length=2,
                        null=True,
                        verbose_name="身份",
                    ),
                ),
                (
                    "job_level",
                    models.CharField(
                        blank=True,
                        help_text="职务职级",
                        max_length=100,
                        null=True,
                        verbose_name="职务职级",
                    ),
                ),
                (
                    "dept_name",
                    models.CharField(
                        blank=True,
                        help_text="单位名称",
                        max_length=100,
                        null=True,
                        verbose_name="单位名称",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        blank=True, help_text="参公时间", null=True, verbose_name="参公时间"
                    ),
                ),
                (
                    "political_status",
                    models.CharField(
                        blank=True,
                        choices=[("0", "中共党员"), ("1", "共青团员"), ("2", "群众")],
                        default="0",
                        help_text="政治面貌",
                        max_length=5,
                        null=True,
                        verbose_name="政治面貌",
                    ),
                ),
                (
                    "brief_achievements",
                    models.TextField(
                        blank=True, help_text="简要事迹", null=True, verbose_name="简要事迹"
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        blank=True,
                        help_text="对应政策",
                        max_length=100,
                        null=True,
                        verbose_name="对应政策",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, help_text="备注", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "优抚一件事-人员管理-基本信息",
                "verbose_name_plural": "优抚一件事-人员管理-基本信息",
                "db_table": "pension_personal_info",
                "ordering": ("-create_datetime",),
            },
        ),
    ]
