# Generated by Django 4.2.1 on 2026-03-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_personal_info", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalinfo",
            old_name="police_number",
            new_name="policer_number",
        ),
    ]
